services:
  - type: web
    name: order-management-api
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    branch: main
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
